// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: emails.proto

package domain

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

//EmailParams holds payload to send an email
type EmailParams struct {
	Em   string `protobuf:"bytes,1,opt,name=em,proto3" json:"em" db:"em"`
	Lang string `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang" db:"lang"`
}

func (m *EmailParams) Reset()         { *m = EmailParams{} }
func (m *EmailParams) String() string { return proto.CompactTextString(m) }
func (*EmailParams) ProtoMessage()    {}
func (*EmailParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee0b3a5d3524f34c, []int{0}
}
func (m *EmailParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EmailParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EmailParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EmailParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailParams.Merge(m, src)
}
func (m *EmailParams) XXX_Size() int {
	return m.Size()
}
func (m *EmailParams) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailParams.DiscardUnknown(m)
}

var xxx_messageInfo_EmailParams proto.InternalMessageInfo

func (m *EmailParams) GetEm() string {
	if m != nil {
		return m.Em
	}
	return ""
}

func (m *EmailParams) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

type EmailResp struct {
	Uid    string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Server string `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
}

func (m *EmailResp) Reset()         { *m = EmailResp{} }
func (m *EmailResp) String() string { return proto.CompactTextString(m) }
func (*EmailResp) ProtoMessage()    {}
func (*EmailResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee0b3a5d3524f34c, []int{1}
}
func (m *EmailResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EmailResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EmailResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EmailResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailResp.Merge(m, src)
}
func (m *EmailResp) XXX_Size() int {
	return m.Size()
}
func (m *EmailResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailResp.DiscardUnknown(m)
}

var xxx_messageInfo_EmailResp proto.InternalMessageInfo

func (m *EmailResp) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *EmailResp) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

func init() {
	proto.RegisterType((*EmailParams)(nil), "domain.EmailParams")
	proto.RegisterType((*EmailResp)(nil), "domain.EmailResp")
}

func init() { proto.RegisterFile("emails.proto", fileDescriptor_ee0b3a5d3524f34c) }

var fileDescriptor_ee0b3a5d3524f34c = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x9b, 0x80, 0x82, 0x6a, 0x18, 0xa8, 0xf9, 0x51, 0xd5, 0x21, 0x81, 0x48, 0x48, 0x30,
	0x90, 0x48, 0x20, 0x16, 0x40, 0xa0, 0x16, 0xb1, 0x57, 0x61, 0x83, 0xc9, 0xa9, 0x6f, 0xd3, 0xa8,
	0x75, 0x1c, 0xd9, 0x09, 0x7d, 0x0d, 0xde, 0x89, 0x85, 0xb1, 0x23, 0x53, 0x84, 0xda, 0xad, 0x63,
	0x9f, 0x00, 0xf9, 0x86, 0xa1, 0x6c, 0xb0, 0x9d, 0x73, 0x7c, 0xbf, 0x63, 0x5b, 0x97, 0xec, 0x80,
	0x60, 0xe9, 0x44, 0x07, 0xb9, 0x92, 0x85, 0xa4, 0x0e, 0x97, 0x82, 0xa5, 0x59, 0xe7, 0x3c, 0x49,
	0x8b, 0x51, 0x19, 0x07, 0x03, 0x29, 0xc2, 0x44, 0x26, 0x32, 0xc4, 0xe3, 0xb8, 0x1c, 0xa2, 0x43,
	0x83, 0xaa, 0xc6, 0xfc, 0x17, 0xb2, 0xfd, 0x68, 0x6a, 0xfa, 0x4c, 0x31, 0xa1, 0xe9, 0x31, 0xb1,
	0x41, 0xb4, 0xad, 0x23, 0xeb, 0xb4, 0xd9, 0x6b, 0x2d, 0x2b, 0xcf, 0x06, 0xb1, 0xaa, 0xbc, 0x2d,
	0x1e, 0x5f, 0xfb, 0x20, 0xfc, 0xc8, 0x06, 0x41, 0xcf, 0xc8, 0xe6, 0x84, 0x65, 0x49, 0xdb, 0xc6,
	0xa1, 0x83, 0x65, 0xe5, 0xa1, 0x5f, 0x55, 0x5e, 0xd3, 0x8c, 0x19, 0xed, 0x47, 0x18, 0xf9, 0x57,
	0xa4, 0x89, 0xe5, 0x11, 0xe8, 0x9c, 0xee, 0x92, 0x8d, 0x32, 0xe5, 0x75, 0x77, 0x64, 0x24, 0x3d,
	0x24, 0x8e, 0x06, 0xf5, 0x0a, 0xaa, 0xee, 0x8a, 0x7e, 0xdc, 0xc5, 0xbb, 0x45, 0x1c, 0xe4, 0x34,
	0xbd, 0x25, 0xf4, 0x09, 0x32, 0xde, 0x1d, 0x0c, 0x64, 0x99, 0x15, 0x0f, 0x32, 0x1b, 0xa6, 0x4a,
	0xd0, 0xbd, 0xa0, 0xfe, 0x6c, 0xb0, 0xf6, 0xf4, 0x4e, 0xeb, 0x57, 0x88, 0x57, 0xde, 0x91, 0x7d,
	0x43, 0x63, 0xd0, 0xe5, 0x5c, 0xfd, 0x97, 0xbf, 0x21, 0x2d, 0xc3, 0xf7, 0x99, 0xd6, 0x53, 0xa9,
	0x78, 0x04, 0x1a, 0x8a, 0xbf, 0xc2, 0xbd, 0xfb, 0x8f, 0xb9, 0x6b, 0xcd, 0xe6, 0xae, 0xf5, 0x35,
	0x77, 0xad, 0xb7, 0x85, 0xdb, 0x98, 0x2d, 0xdc, 0xc6, 0xe7, 0xc2, 0x6d, 0x3c, 0x9f, 0xac, 0xad,
	0x68, 0x3c, 0x61, 0x23, 0xad, 0x21, 0x0b, 0xa7, 0x10, 0xb3, 0x3c, 0x0f, 0xf3, 0x71, 0x12, 0xd6,
	0x55, 0xb1, 0x83, 0x1b, 0xba, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x28, 0xda, 0xc7, 0xe8,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmailsClient is the client API for Emails service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmailsClient interface {
	SendAccountConfirm(ctx context.Context, in *EmailParams, opts ...grpc.CallOption) (*EmailResp, error)
	SendEmailAddrConfirm(ctx context.Context, in *EmailParams, opts ...grpc.CallOption) (*EmailResp, error)
	SendPasswordReset(ctx context.Context, in *EmailParams, opts ...grpc.CallOption) (*EmailResp, error)
}

type emailsClient struct {
	cc *grpc.ClientConn
}

func NewEmailsClient(cc *grpc.ClientConn) EmailsClient {
	return &emailsClient{cc}
}

func (c *emailsClient) SendAccountConfirm(ctx context.Context, in *EmailParams, opts ...grpc.CallOption) (*EmailResp, error) {
	out := new(EmailResp)
	err := c.cc.Invoke(ctx, "/domain.Emails/SendAccountConfirm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailsClient) SendEmailAddrConfirm(ctx context.Context, in *EmailParams, opts ...grpc.CallOption) (*EmailResp, error) {
	out := new(EmailResp)
	err := c.cc.Invoke(ctx, "/domain.Emails/SendEmailAddrConfirm", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailsClient) SendPasswordReset(ctx context.Context, in *EmailParams, opts ...grpc.CallOption) (*EmailResp, error) {
	out := new(EmailResp)
	err := c.cc.Invoke(ctx, "/domain.Emails/SendPasswordReset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailsServer is the server API for Emails service.
type EmailsServer interface {
	SendAccountConfirm(context.Context, *EmailParams) (*EmailResp, error)
	SendEmailAddrConfirm(context.Context, *EmailParams) (*EmailResp, error)
	SendPasswordReset(context.Context, *EmailParams) (*EmailResp, error)
}

func RegisterEmailsServer(s *grpc.Server, srv EmailsServer) {
	s.RegisterService(&_Emails_serviceDesc, srv)
}

func _Emails_SendAccountConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailsServer).SendAccountConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/domain.Emails/SendAccountConfirm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailsServer).SendAccountConfirm(ctx, req.(*EmailParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Emails_SendEmailAddrConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailsServer).SendEmailAddrConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/domain.Emails/SendEmailAddrConfirm",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailsServer).SendEmailAddrConfirm(ctx, req.(*EmailParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Emails_SendPasswordReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailsServer).SendPasswordReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/domain.Emails/SendPasswordReset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailsServer).SendPasswordReset(ctx, req.(*EmailParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Emails_serviceDesc = grpc.ServiceDesc{
	ServiceName: "domain.Emails",
	HandlerType: (*EmailsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendAccountConfirm",
			Handler:    _Emails_SendAccountConfirm_Handler,
		},
		{
			MethodName: "SendEmailAddrConfirm",
			Handler:    _Emails_SendEmailAddrConfirm_Handler,
		},
		{
			MethodName: "SendPasswordReset",
			Handler:    _Emails_SendPasswordReset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emails.proto",
}

func (m *EmailParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EmailParams) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Em) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintEmails(dAtA, i, uint64(len(m.Em)))
		i += copy(dAtA[i:], m.Em)
	}
	if len(m.Lang) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintEmails(dAtA, i, uint64(len(m.Lang)))
		i += copy(dAtA[i:], m.Lang)
	}
	return i, nil
}

func (m *EmailResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EmailResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Uid) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintEmails(dAtA, i, uint64(len(m.Uid)))
		i += copy(dAtA[i:], m.Uid)
	}
	if len(m.Server) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintEmails(dAtA, i, uint64(len(m.Server)))
		i += copy(dAtA[i:], m.Server)
	}
	return i, nil
}

func encodeVarintEmails(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *EmailParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Em)
	if l > 0 {
		n += 1 + l + sovEmails(uint64(l))
	}
	l = len(m.Lang)
	if l > 0 {
		n += 1 + l + sovEmails(uint64(l))
	}
	return n
}

func (m *EmailResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Uid)
	if l > 0 {
		n += 1 + l + sovEmails(uint64(l))
	}
	l = len(m.Server)
	if l > 0 {
		n += 1 + l + sovEmails(uint64(l))
	}
	return n
}

func sovEmails(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozEmails(x uint64) (n int) {
	return sovEmails(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EmailParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEmails
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmailParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmailParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Em", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmails
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmails
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmails
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Em = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lang", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmails
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmails
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmails
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Lang = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEmails(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEmails
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthEmails
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EmailResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEmails
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmailResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmailResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmails
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmails
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmails
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Server", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEmails
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEmails
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEmails
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Server = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEmails(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthEmails
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthEmails
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEmails(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEmails
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEmails
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEmails
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEmails
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthEmails
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowEmails
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipEmails(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthEmails
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthEmails = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEmails   = fmt.Errorf("proto: integer overflow")
)
