// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: accounts.proto

package domain

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	io "io"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

//AccountType is an authorization criteria
type AccountType int32

const (
	AccountType_USER  AccountType = 0
	AccountType_ADMIN AccountType = 1
	AccountType_DEV   AccountType = 2
)

var AccountType_name = map[int32]string{
	0: "USER",
	1: "ADMIN",
	2: "DEV",
}

var AccountType_value = map[string]int32{
	"USER":  0,
	"ADMIN": 1,
	"DEV":   2,
}

func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}

func (AccountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{0}
}

//AccountStatus is an authorization criteria
type AccountStatus int32

const (
	AccountStatus_CREATED  AccountStatus = 0
	AccountStatus_ACTIVE   AccountStatus = 1
	AccountStatus_LOCKED   AccountStatus = 2
	AccountStatus_INACTIVE AccountStatus = 3
	AccountStatus_DELETED  AccountStatus = 4
)

var AccountStatus_name = map[int32]string{
	0: "CREATED",
	1: "ACTIVE",
	2: "LOCKED",
	3: "INACTIVE",
	4: "DELETED",
}

var AccountStatus_value = map[string]int32{
	"CREATED":  0,
	"ACTIVE":   1,
	"LOCKED":   2,
	"INACTIVE": 3,
	"DELETED":  4,
}

func (x AccountStatus) String() string {
	return proto.EnumName(AccountStatus_name, int32(x))
}

func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{1}
}

//AccountEntity (timestamps in seconds)
type AccountEntity struct {
	// `datastore:"-"`
	Uid           string        `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid" db:"uid"`
	Em            string        `protobuf:"bytes,3,opt,name=em,json=email,proto3" json:"email" db:"email"`
	Pw            string        `protobuf:"bytes,4,opt,name=pw,json=-,proto3" json:"-" db:"pw"`
	CreatedAt     int64         `protobuf:"varint,5,opt,name=created_at,json=crea_at,proto3" json:"crea_at" db:"crea_at"`
	UpdatedAt     int64         `protobuf:"varint,6,opt,name=updated_at,json=upd_at,proto3" json:"upd_at" db:"upd_at"`
	Type          AccountType   `protobuf:"varint,7,opt,name=type,proto3,enum=domain.AccountType" json:"type" db:"type"`
	Status        AccountStatus `protobuf:"varint,8,opt,name=status,proto3,enum=domain.AccountStatus" json:"status" db:"status"`
	ParentAccount string        `protobuf:"bytes,9,opt,name=parent_account,json=parent,proto3" json:"parent" db:"parent"`
}

func (m *AccountEntity) Reset()         { *m = AccountEntity{} }
func (m *AccountEntity) String() string { return proto.CompactTextString(m) }
func (*AccountEntity) ProtoMessage()    {}
func (*AccountEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{0}
}
func (m *AccountEntity) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountEntity.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountEntity.Merge(m, src)
}
func (m *AccountEntity) XXX_Size() int {
	return m.Size()
}
func (m *AccountEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountEntity.DiscardUnknown(m)
}

var xxx_messageInfo_AccountEntity proto.InternalMessageInfo

func (m *AccountEntity) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AccountEntity) GetEm() string {
	if m != nil {
		return m.Em
	}
	return ""
}

func (m *AccountEntity) GetPw() string {
	if m != nil {
		return m.Pw
	}
	return ""
}

func (m *AccountEntity) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *AccountEntity) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *AccountEntity) GetType() AccountType {
	if m != nil {
		return m.Type
	}
	return AccountType_USER
}

func (m *AccountEntity) GetStatus() AccountStatus {
	if m != nil {
		return m.Status
	}
	return AccountStatus_CREATED
}

func (m *AccountEntity) GetParentAccount() string {
	if m != nil {
		return m.ParentAccount
	}
	return ""
}

type AccountID struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *AccountID) Reset()         { *m = AccountID{} }
func (m *AccountID) String() string { return proto.CompactTextString(m) }
func (*AccountID) ProtoMessage()    {}
func (*AccountID) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{1}
}
func (m *AccountID) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountID.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountID.Merge(m, src)
}
func (m *AccountID) XXX_Size() int {
	return m.Size()
}
func (m *AccountID) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountID.DiscardUnknown(m)
}

var xxx_messageInfo_AccountID proto.InternalMessageInfo

func (m *AccountID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

//AccountParams holds payload to create/update an Account
type AccountParams struct {
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Em  string `protobuf:"bytes,2,opt,name=em,proto3" json:"em,omitempty"`
	Pw  string `protobuf:"bytes,3,opt,name=pw,proto3" json:"pw,omitempty"`
}

func (m *AccountParams) Reset()         { *m = AccountParams{} }
func (m *AccountParams) String() string { return proto.CompactTextString(m) }
func (*AccountParams) ProtoMessage()    {}
func (*AccountParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{2}
}
func (m *AccountParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountParams.Merge(m, src)
}
func (m *AccountParams) XXX_Size() int {
	return m.Size()
}
func (m *AccountParams) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountParams.DiscardUnknown(m)
}

var xxx_messageInfo_AccountParams proto.InternalMessageInfo

func (m *AccountParams) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AccountParams) GetEm() string {
	if m != nil {
		return m.Em
	}
	return ""
}

func (m *AccountParams) GetPw() string {
	if m != nil {
		return m.Pw
	}
	return ""
}

//AccountResp holds response for Account creation or update
type AccountResp struct {
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (m *AccountResp) Reset()         { *m = AccountResp{} }
func (m *AccountResp) String() string { return proto.CompactTextString(m) }
func (*AccountResp) ProtoMessage()    {}
func (*AccountResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{3}
}
func (m *AccountResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountResp.Merge(m, src)
}
func (m *AccountResp) XXX_Size() int {
	return m.Size()
}
func (m *AccountResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountResp.DiscardUnknown(m)
}

var xxx_messageInfo_AccountResp proto.InternalMessageInfo

func (m *AccountResp) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

//AccountJwtTokens holds authentication tokens
type AccountJwtTokens struct {
	Access  string `protobuf:"bytes,1,opt,name=access,proto3" json:"access,omitempty"`
	Refresh string `protobuf:"bytes,2,opt,name=refresh,proto3" json:"refresh,omitempty"`
}

func (m *AccountJwtTokens) Reset()         { *m = AccountJwtTokens{} }
func (m *AccountJwtTokens) String() string { return proto.CompactTextString(m) }
func (*AccountJwtTokens) ProtoMessage()    {}
func (*AccountJwtTokens) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{4}
}
func (m *AccountJwtTokens) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountJwtTokens) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountJwtTokens.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountJwtTokens) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountJwtTokens.Merge(m, src)
}
func (m *AccountJwtTokens) XXX_Size() int {
	return m.Size()
}
func (m *AccountJwtTokens) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountJwtTokens.DiscardUnknown(m)
}

var xxx_messageInfo_AccountJwtTokens proto.InternalMessageInfo

func (m *AccountJwtTokens) GetAccess() string {
	if m != nil {
		return m.Access
	}
	return ""
}

func (m *AccountJwtTokens) GetRefresh() string {
	if m != nil {
		return m.Refresh
	}
	return ""
}

//AccountCredentials holds credentials to authenticate a user
type AccountCredentials struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pw string `protobuf:"bytes,2,opt,name=pw,proto3" json:"pw,omitempty"`
}

func (m *AccountCredentials) Reset()         { *m = AccountCredentials{} }
func (m *AccountCredentials) String() string { return proto.CompactTextString(m) }
func (*AccountCredentials) ProtoMessage()    {}
func (*AccountCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{5}
}
func (m *AccountCredentials) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountCredentials.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountCredentials.Merge(m, src)
}
func (m *AccountCredentials) XXX_Size() int {
	return m.Size()
}
func (m *AccountCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_AccountCredentials proto.InternalMessageInfo

func (m *AccountCredentials) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AccountCredentials) GetPw() string {
	if m != nil {
		return m.Pw
	}
	return ""
}

//AccountParams holds payload to create/update an Account
type AccountPrivileges struct {
	Uid    string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Type   string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Status string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (m *AccountPrivileges) Reset()         { *m = AccountPrivileges{} }
func (m *AccountPrivileges) String() string { return proto.CompactTextString(m) }
func (*AccountPrivileges) ProtoMessage()    {}
func (*AccountPrivileges) Descriptor() ([]byte, []int) {
	return fileDescriptor_e1e7723af4c007b7, []int{6}
}
func (m *AccountPrivileges) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountPrivileges) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountPrivileges.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountPrivileges) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountPrivileges.Merge(m, src)
}
func (m *AccountPrivileges) XXX_Size() int {
	return m.Size()
}
func (m *AccountPrivileges) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountPrivileges.DiscardUnknown(m)
}

var xxx_messageInfo_AccountPrivileges proto.InternalMessageInfo

func (m *AccountPrivileges) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AccountPrivileges) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AccountPrivileges) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterEnum("domain.AccountType", AccountType_name, AccountType_value)
	proto.RegisterEnum("domain.AccountStatus", AccountStatus_name, AccountStatus_value)
	proto.RegisterType((*AccountEntity)(nil), "domain.AccountEntity")
	proto.RegisterType((*AccountID)(nil), "domain.AccountID")
	proto.RegisterType((*AccountParams)(nil), "domain.AccountParams")
	proto.RegisterType((*AccountResp)(nil), "domain.AccountResp")
	proto.RegisterType((*AccountJwtTokens)(nil), "domain.AccountJwtTokens")
	proto.RegisterType((*AccountCredentials)(nil), "domain.AccountCredentials")
	proto.RegisterType((*AccountPrivileges)(nil), "domain.AccountPrivileges")
}

func init() { proto.RegisterFile("accounts.proto", fileDescriptor_e1e7723af4c007b7) }

var fileDescriptor_e1e7723af4c007b7 = []byte{
	// 745 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x4e, 0xe3, 0x56,
	0x14, 0x8e, 0xed, 0xe0, 0x24, 0x27, 0x69, 0x64, 0x2e, 0x82, 0x9a, 0x20, 0xc5, 0xd4, 0x52, 0x25,
	0x44, 0x45, 0x22, 0x51, 0x2a, 0x95, 0xb6, 0x42, 0x4a, 0x62, 0xab, 0x4d, 0x87, 0x01, 0xc6, 0x04,
	0x16, 0xb3, 0x41, 0x4e, 0x7c, 0x49, 0x2c, 0x92, 0xd8, 0xb2, 0xaf, 0x27, 0xe2, 0x2d, 0xe6, 0x49,
	0x66, 0x3f, 0x6f, 0x30, 0x4b, 0x96, 0xb3, 0xb2, 0x46, 0xb0, 0xcb, 0x32, 0x4f, 0x30, 0xba, 0x3f,
	0x89, 0x90, 0x87, 0x0d, 0x3b, 0x7f, 0xe7, 0x7c, 0xdf, 0xf1, 0x3d, 0xe7, 0x3b, 0xf7, 0x42, 0xd5,
	0x1d, 0x0c, 0x82, 0x64, 0x4a, 0xe2, 0x46, 0x18, 0x05, 0x24, 0x40, 0xaa, 0x17, 0x4c, 0x5c, 0x7f,
	0x5a, 0x3b, 0x18, 0xfa, 0x64, 0x94, 0xf4, 0x1b, 0x83, 0x60, 0xd2, 0x1c, 0x06, 0xc3, 0xa0, 0xc9,
	0xd2, 0xfd, 0xe4, 0x96, 0x21, 0x06, 0xd8, 0x17, 0x97, 0x99, 0x9f, 0x15, 0xf8, 0xa9, 0xc5, 0x2b,
	0xd9, 0x53, 0xe2, 0x93, 0x7b, 0xf4, 0x2b, 0x28, 0x89, 0xef, 0xe9, 0xd2, 0xae, 0xb4, 0x57, 0x6a,
	0x6f, 0xcc, 0x53, 0x83, 0xc2, 0x45, 0x6a, 0x14, 0xbd, 0xfe, 0x5f, 0x66, 0xe2, 0x7b, 0xa6, 0x43,
	0x03, 0x68, 0x1f, 0x64, 0x3c, 0xd1, 0x15, 0xc6, 0xfa, 0x79, 0x9e, 0x1a, 0x6b, 0x78, 0xe2, 0xfa,
	0xe3, 0x45, 0x6a, 0x00, 0xe5, 0x31, 0x60, 0x3a, 0x3c, 0x88, 0x0c, 0x90, 0xc3, 0x99, 0x9e, 0x67,
	0x5c, 0x6d, 0x9e, 0x1a, 0xd2, 0xc1, 0x22, 0x35, 0x0a, 0x94, 0x17, 0xce, 0x4c, 0x47, 0x3a, 0x40,
	0x7f, 0x02, 0x0c, 0x22, 0xec, 0x12, 0xec, 0xdd, 0xb8, 0x44, 0x5f, 0xdb, 0x95, 0xf6, 0x94, 0xf6,
	0xce, 0x3c, 0x35, 0x0a, 0x34, 0x7a, 0xe3, 0x92, 0x45, 0x6a, 0x54, 0x28, 0x5d, 0x40, 0xd3, 0x59,
	0x26, 0xd0, 0x1f, 0x00, 0x49, 0xe8, 0x2d, 0x95, 0x2a, 0x53, 0x6e, 0xcf, 0x53, 0x43, 0x4d, 0x42,
	0x8f, 0x0b, 0xcb, 0xec, 0xdc, 0x0c, 0x99, 0x8e, 0x08, 0xa3, 0x13, 0xc8, 0x93, 0xfb, 0x10, 0xeb,
	0x85, 0x5d, 0x69, 0xaf, 0x7a, 0xb8, 0xd1, 0xe0, 0xc3, 0x6b, 0x88, 0x49, 0xf4, 0xee, 0x43, 0xdc,
	0xde, 0x9c, 0xa7, 0x06, 0x23, 0x2d, 0x52, 0xa3, 0x44, 0x6b, 0xd0, 0x6f, 0xd3, 0x61, 0x21, 0xf4,
	0x1f, 0xa8, 0x31, 0x71, 0x49, 0x12, 0xeb, 0x45, 0x56, 0x61, 0x33, 0x53, 0xe1, 0x92, 0x25, 0xf9,
	0x49, 0x38, 0x71, 0x79, 0x12, 0x8e, 0x4c, 0x47, 0x84, 0xd1, 0x31, 0x54, 0x43, 0x37, 0xc2, 0x53,
	0x72, 0x23, 0x0c, 0xd5, 0x4b, 0x6c, 0x4e, 0x4c, 0xca, 0x33, 0x4b, 0x29, 0x47, 0xa6, 0x23, 0xc2,
	0xe6, 0x0e, 0x94, 0xc4, 0xef, 0xba, 0x16, 0xaa, 0x82, 0xbc, 0x74, 0xcd, 0x91, 0x7d, 0xcf, 0x6c,
	0xad, 0x7c, 0xbd, 0x70, 0x23, 0x77, 0x12, 0x23, 0xed, 0x99, 0xaf, 0xdc, 0xc2, 0x2a, 0xb3, 0x50,
	0xe6, 0x12, 0x3c, 0xa1, 0x38, 0x9c, 0x71, 0x4b, 0x1d, 0x39, 0x9c, 0x99, 0x06, 0x94, 0x45, 0x09,
	0x07, 0xc7, 0xe1, 0x8f, 0x05, 0x4c, 0x0b, 0x34, 0x41, 0xf8, 0x7f, 0x46, 0x7a, 0xc1, 0x1d, 0x9e,
	0xc6, 0x68, 0x0b, 0x54, 0x77, 0x30, 0xc0, 0x71, 0x2c, 0x88, 0x02, 0x21, 0x1d, 0x0a, 0x11, 0xbe,
	0x8d, 0x70, 0x3c, 0x12, 0x7f, 0x5c, 0x42, 0xf3, 0x08, 0x90, 0xa8, 0xd2, 0x89, 0xb0, 0x87, 0xa7,
	0xc4, 0x77, 0xc7, 0x71, 0xb6, 0x1f, 0x71, 0x38, 0x79, 0x75, 0xb8, 0x77, 0xb0, 0xbe, 0xec, 0x2f,
	0xf2, 0x3f, 0xf8, 0x63, 0x3c, 0xc4, 0x2f, 0xf5, 0x88, 0x84, 0xd1, 0x5c, 0xc8, 0xcd, 0xdb, 0x5a,
	0x99, 0xc7, 0x7b, 0x15, 0x68, 0xff, 0xb7, 0x55, 0xbf, 0x74, 0x01, 0x50, 0x11, 0xf2, 0x57, 0x97,
	0xb6, 0xa3, 0xe5, 0x50, 0x09, 0xd6, 0x5a, 0xd6, 0xdb, 0xee, 0x99, 0x26, 0xa1, 0x02, 0x28, 0x96,
	0x7d, 0xad, 0xc9, 0xfb, 0xe7, 0xab, 0xf9, 0x72, 0xaf, 0x51, 0x19, 0x0a, 0x1d, 0xc7, 0x6e, 0xf5,
	0x6c, 0x4b, 0xcb, 0x21, 0x00, 0xb5, 0xd5, 0xe9, 0x75, 0xaf, 0x6d, 0x4d, 0xa2, 0xdf, 0xa7, 0xe7,
	0x9d, 0x37, 0xb6, 0xa5, 0xc9, 0xa8, 0x02, 0xc5, 0xee, 0x99, 0xc8, 0x28, 0x54, 0x62, 0xd9, 0xa7,
	0x36, 0x95, 0xe4, 0x0f, 0x3f, 0x29, 0x50, 0x14, 0x15, 0x63, 0x74, 0x04, 0x6a, 0x87, 0x5d, 0x08,
	0x94, 0xdd, 0x2c, 0xee, 0x66, 0x2d, 0xbb, 0xb2, 0xcc, 0xa1, 0x63, 0x28, 0x5f, 0xb1, 0xcb, 0x60,
	0xb3, 0x6b, 0xf7, 0x1a, 0xe9, 0x3f, 0x50, 0xe5, 0xd2, 0x0b, 0x37, 0x8e, 0x67, 0x41, 0xe4, 0xbd,
	0x52, 0x0d, 0x5c, 0xcd, 0x06, 0xb7, 0x9d, 0x55, 0xae, 0x0c, 0x7a, 0x59, 0x7d, 0x02, 0x15, 0xae,
	0x16, 0x93, 0x7c, 0xad, 0xbe, 0x09, 0xca, 0xbf, 0x98, 0xa0, 0xf5, 0x4c, 0xae, 0x6b, 0xd5, 0xb2,
	0x3d, 0x88, 0x27, 0xce, 0x82, 0x4a, 0x2b, 0x21, 0x23, 0xba, 0x6a, 0x03, 0x3a, 0xe3, 0x5a, 0x86,
	0xf6, 0x6c, 0x0f, 0x6b, 0x7a, 0x26, 0xb7, 0xda, 0xf4, 0xf6, 0xdf, 0x5f, 0x1e, 0xeb, 0xd2, 0xc3,
	0x63, 0x5d, 0xfa, 0xf6, 0x58, 0x97, 0x3e, 0x3e, 0xd5, 0x73, 0x0f, 0x4f, 0xf5, 0xdc, 0xd7, 0xa7,
	0x7a, 0xee, 0xfd, 0x2f, 0xcf, 0xde, 0xe0, 0xbb, 0xb1, 0x3b, 0x8a, 0x63, 0x3c, 0x6d, 0xce, 0x70,
	0xdf, 0x0d, 0xc3, 0x26, 0xaf, 0xd6, 0x57, 0xd9, 0xf3, 0xfb, 0xfb, 0xf7, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x23, 0xe0, 0xd7, 0xe9, 0xc7, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountsClient is the client API for Accounts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountsClient interface {
	Create(ctx context.Context, in *AccountParams, opts ...grpc.CallOption) (*AccountResp, error)
	UpdateEmail(ctx context.Context, in *AccountParams, opts ...grpc.CallOption) (*AccountResp, error)
	UpdatePassword(ctx context.Context, in *AccountParams, opts ...grpc.CallOption) (*AccountResp, error)
	UpdateType(ctx context.Context, in *AccountPrivileges, opts ...grpc.CallOption) (*AccountResp, error)
	UpdateStatus(ctx context.Context, in *AccountPrivileges, opts ...grpc.CallOption) (*AccountResp, error)
	Get(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*AccountEntity, error)
	Authenticate(ctx context.Context, in *AccountCredentials, opts ...grpc.CallOption) (*AccountJwtTokens, error)
}

type accountsClient struct {
	cc *grpc.ClientConn
}

func NewAccountsClient(cc *grpc.ClientConn) AccountsClient {
	return &accountsClient{cc}
}

func (c *accountsClient) Create(ctx context.Context, in *AccountParams, opts ...grpc.CallOption) (*AccountResp, error) {
	out := new(AccountResp)
	err := c.cc.Invoke(ctx, "/domain.Accounts/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) UpdateEmail(ctx context.Context, in *AccountParams, opts ...grpc.CallOption) (*AccountResp, error) {
	out := new(AccountResp)
	err := c.cc.Invoke(ctx, "/domain.Accounts/UpdateEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) UpdatePassword(ctx context.Context, in *AccountParams, opts ...grpc.CallOption) (*AccountResp, error) {
	out := new(AccountResp)
	err := c.cc.Invoke(ctx, "/domain.Accounts/UpdatePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) UpdateType(ctx context.Context, in *AccountPrivileges, opts ...grpc.CallOption) (*AccountResp, error) {
	out := new(AccountResp)
	err := c.cc.Invoke(ctx, "/domain.Accounts/UpdateType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) UpdateStatus(ctx context.Context, in *AccountPrivileges, opts ...grpc.CallOption) (*AccountResp, error) {
	out := new(AccountResp)
	err := c.cc.Invoke(ctx, "/domain.Accounts/UpdateStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) Get(ctx context.Context, in *AccountID, opts ...grpc.CallOption) (*AccountEntity, error) {
	out := new(AccountEntity)
	err := c.cc.Invoke(ctx, "/domain.Accounts/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsClient) Authenticate(ctx context.Context, in *AccountCredentials, opts ...grpc.CallOption) (*AccountJwtTokens, error) {
	out := new(AccountJwtTokens)
	err := c.cc.Invoke(ctx, "/domain.Accounts/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsServer is the server API for Accounts service.
type AccountsServer interface {
	Create(context.Context, *AccountParams) (*AccountResp, error)
	UpdateEmail(context.Context, *AccountParams) (*AccountResp, error)
	UpdatePassword(context.Context, *AccountParams) (*AccountResp, error)
	UpdateType(context.Context, *AccountPrivileges) (*AccountResp, error)
	UpdateStatus(context.Context, *AccountPrivileges) (*AccountResp, error)
	Get(context.Context, *AccountID) (*AccountEntity, error)
	Authenticate(context.Context, *AccountCredentials) (*AccountJwtTokens, error)
}

func RegisterAccountsServer(s *grpc.Server, srv AccountsServer) {
	s.RegisterService(&_Accounts_serviceDesc, srv)
}

func _Accounts_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/domain.Accounts/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).Create(ctx, req.(*AccountParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_UpdateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).UpdateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/domain.Accounts/UpdateEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).UpdateEmail(ctx, req.(*AccountParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/domain.Accounts/UpdatePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).UpdatePassword(ctx, req.(*AccountParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_UpdateType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountPrivileges)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).UpdateType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/domain.Accounts/UpdateType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).UpdateType(ctx, req.(*AccountPrivileges))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountPrivileges)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/domain.Accounts/UpdateStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).UpdateStatus(ctx, req.(*AccountPrivileges))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/domain.Accounts/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).Get(ctx, req.(*AccountID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Accounts_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountCredentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/domain.Accounts/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsServer).Authenticate(ctx, req.(*AccountCredentials))
	}
	return interceptor(ctx, in, info, handler)
}

var _Accounts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "domain.Accounts",
	HandlerType: (*AccountsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Accounts_Create_Handler,
		},
		{
			MethodName: "UpdateEmail",
			Handler:    _Accounts_UpdateEmail_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _Accounts_UpdatePassword_Handler,
		},
		{
			MethodName: "UpdateType",
			Handler:    _Accounts_UpdateType_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _Accounts_UpdateStatus_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Accounts_Get_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _Accounts_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accounts.proto",
}

func (m *AccountEntity) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountEntity) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Uid) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAccounts(dAtA, i, uint64(len(m.Uid)))
		i += copy(dAtA[i:], m.Uid)
	}
	if len(m.Em) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintAccounts(dAtA, i, uint64(len(m.Em)))
		i += copy(dAtA[i:], m.Em)
	}
	if len(m.Pw) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintAccounts(dAtA, i, uint64(len(m.Pw)))
		i += copy(dAtA[i:], m.Pw)
	}
	if m.CreatedAt != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintAccounts(dAtA, i, uint64(m.CreatedAt))
	}
	if m.UpdatedAt != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintAccounts(dAtA, i, uint64(m.UpdatedAt))
	}
	if m.Type != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintAccounts(dAtA, i, uint64(m.Type))
	}
	if m.Status != 0 {
		dAtA[i] = 0x40
		i++
		i = encodeVarintAccounts(dAtA, i, uint64(m.Status))
	}
	if len(m.ParentAccount) > 0 {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintAccounts(dAtA, i, uint64(len(m.ParentAccount)))
		i += copy(dAtA[i:], m.ParentAccount)
	}
	return i, nil
}

func (m *AccountID) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountID) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAccounts(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	return i, nil
}

func (m *AccountParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountParams) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Uid) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAccounts(dAtA, i, uint64(len(m.Uid)))
		i += copy(dAtA[i:], m.Uid)
	}
	if len(m.Em) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintAccounts(dAtA, i, uint64(len(m.Em)))
		i += copy(dAtA[i:], m.Em)
	}
	if len(m.Pw) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintAccounts(dAtA, i, uint64(len(m.Pw)))
		i += copy(dAtA[i:], m.Pw)
	}
	return i, nil
}

func (m *AccountResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountResp) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Uid) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAccounts(dAtA, i, uint64(len(m.Uid)))
		i += copy(dAtA[i:], m.Uid)
	}
	return i, nil
}

func (m *AccountJwtTokens) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountJwtTokens) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Access) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAccounts(dAtA, i, uint64(len(m.Access)))
		i += copy(dAtA[i:], m.Access)
	}
	if len(m.Refresh) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintAccounts(dAtA, i, uint64(len(m.Refresh)))
		i += copy(dAtA[i:], m.Refresh)
	}
	return i, nil
}

func (m *AccountCredentials) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountCredentials) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAccounts(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	if len(m.Pw) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintAccounts(dAtA, i, uint64(len(m.Pw)))
		i += copy(dAtA[i:], m.Pw)
	}
	return i, nil
}

func (m *AccountPrivileges) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountPrivileges) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Uid) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAccounts(dAtA, i, uint64(len(m.Uid)))
		i += copy(dAtA[i:], m.Uid)
	}
	if len(m.Type) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintAccounts(dAtA, i, uint64(len(m.Type)))
		i += copy(dAtA[i:], m.Type)
	}
	if len(m.Status) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintAccounts(dAtA, i, uint64(len(m.Status)))
		i += copy(dAtA[i:], m.Status)
	}
	return i, nil
}

func encodeVarintAccounts(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *AccountEntity) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Uid)
	if l > 0 {
		n += 1 + l + sovAccounts(uint64(l))
	}
	l = len(m.Em)
	if l > 0 {
		n += 1 + l + sovAccounts(uint64(l))
	}
	l = len(m.Pw)
	if l > 0 {
		n += 1 + l + sovAccounts(uint64(l))
	}
	if m.CreatedAt != 0 {
		n += 1 + sovAccounts(uint64(m.CreatedAt))
	}
	if m.UpdatedAt != 0 {
		n += 1 + sovAccounts(uint64(m.UpdatedAt))
	}
	if m.Type != 0 {
		n += 1 + sovAccounts(uint64(m.Type))
	}
	if m.Status != 0 {
		n += 1 + sovAccounts(uint64(m.Status))
	}
	l = len(m.ParentAccount)
	if l > 0 {
		n += 1 + l + sovAccounts(uint64(l))
	}
	return n
}

func (m *AccountID) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovAccounts(uint64(l))
	}
	return n
}

func (m *AccountParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Uid)
	if l > 0 {
		n += 1 + l + sovAccounts(uint64(l))
	}
	l = len(m.Em)
	if l > 0 {
		n += 1 + l + sovAccounts(uint64(l))
	}
	l = len(m.Pw)
	if l > 0 {
		n += 1 + l + sovAccounts(uint64(l))
	}
	return n
}

func (m *AccountResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Uid)
	if l > 0 {
		n += 1 + l + sovAccounts(uint64(l))
	}
	return n
}

func (m *AccountJwtTokens) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Access)
	if l > 0 {
		n += 1 + l + sovAccounts(uint64(l))
	}
	l = len(m.Refresh)
	if l > 0 {
		n += 1 + l + sovAccounts(uint64(l))
	}
	return n
}

func (m *AccountCredentials) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovAccounts(uint64(l))
	}
	l = len(m.Pw)
	if l > 0 {
		n += 1 + l + sovAccounts(uint64(l))
	}
	return n
}

func (m *AccountPrivileges) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Uid)
	if l > 0 {
		n += 1 + l + sovAccounts(uint64(l))
	}
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovAccounts(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovAccounts(uint64(l))
	}
	return n
}

func sovAccounts(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozAccounts(x uint64) (n int) {
	return sovAccounts(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AccountEntity) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccounts
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountEntity: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountEntity: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccounts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccounts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccounts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Em", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccounts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccounts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccounts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Em = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pw", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccounts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccounts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccounts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pw = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccounts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccounts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccounts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= AccountType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccounts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= AccountStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParentAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccounts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccounts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccounts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParentAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccounts(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAccounts
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAccounts
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountID) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccounts
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountID: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountID: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccounts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccounts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccounts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccounts(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAccounts
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAccounts
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccounts
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccounts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccounts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccounts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Em", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccounts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccounts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccounts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Em = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pw", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccounts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccounts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccounts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pw = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccounts(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAccounts
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAccounts
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccounts
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccounts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccounts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccounts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccounts(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAccounts
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAccounts
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountJwtTokens) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccounts
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountJwtTokens: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountJwtTokens: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Access", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccounts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccounts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccounts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Access = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Refresh", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccounts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccounts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccounts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Refresh = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccounts(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAccounts
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAccounts
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountCredentials) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccounts
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountCredentials: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountCredentials: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccounts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccounts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccounts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pw", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccounts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccounts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccounts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pw = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccounts(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAccounts
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAccounts
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountPrivileges) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAccounts
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountPrivileges: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountPrivileges: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccounts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccounts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccounts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccounts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccounts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccounts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAccounts
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAccounts
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAccounts
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAccounts(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAccounts
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAccounts
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAccounts(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAccounts
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAccounts
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAccounts
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAccounts
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthAccounts
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowAccounts
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipAccounts(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthAccounts
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthAccounts = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAccounts   = fmt.Errorf("proto: integer overflow")
)
