// Code generated by protoc-gen-go. DO NOT EDIT.
// source: emails.proto

package domain

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmailType int32

const (
	EmailType_NEW_ACCOUNT  EmailType = 0
	EmailType_NEW_PASSWORD EmailType = 1
)

var EmailType_name = map[int32]string{
	0: "NEW_ACCOUNT",
	1: "NEW_PASSWORD",
}

var EmailType_value = map[string]int32{
	"NEW_ACCOUNT":  0,
	"NEW_PASSWORD": 1,
}

func (x EmailType) String() string {
	return proto.EnumName(EmailType_name, int32(x))
}

func (EmailType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ee0b3a5d3524f34c, []int{0}
}

//EmailParams holds payload to send an email
type EmailParams struct {
	Em                   string    `protobuf:"bytes,1,opt,name=em,proto3" json:"em,omitempty"`
	Lang                 string    `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	Type                 EmailType `protobuf:"varint,3,opt,name=type,proto3,enum=domain.EmailType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EmailParams) Reset()         { *m = EmailParams{} }
func (m *EmailParams) String() string { return proto.CompactTextString(m) }
func (*EmailParams) ProtoMessage()    {}
func (*EmailParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee0b3a5d3524f34c, []int{0}
}

func (m *EmailParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailParams.Unmarshal(m, b)
}
func (m *EmailParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailParams.Marshal(b, m, deterministic)
}
func (m *EmailParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailParams.Merge(m, src)
}
func (m *EmailParams) XXX_Size() int {
	return xxx_messageInfo_EmailParams.Size(m)
}
func (m *EmailParams) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailParams.DiscardUnknown(m)
}

var xxx_messageInfo_EmailParams proto.InternalMessageInfo

func (m *EmailParams) GetEm() string {
	if m != nil {
		return m.Em
	}
	return ""
}

func (m *EmailParams) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *EmailParams) GetType() EmailType {
	if m != nil {
		return m.Type
	}
	return EmailType_NEW_ACCOUNT
}

type EmailResp struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailResp) Reset()         { *m = EmailResp{} }
func (m *EmailResp) String() string { return proto.CompactTextString(m) }
func (*EmailResp) ProtoMessage()    {}
func (*EmailResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ee0b3a5d3524f34c, []int{1}
}

func (m *EmailResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailResp.Unmarshal(m, b)
}
func (m *EmailResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailResp.Marshal(b, m, deterministic)
}
func (m *EmailResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailResp.Merge(m, src)
}
func (m *EmailResp) XXX_Size() int {
	return xxx_messageInfo_EmailResp.Size(m)
}
func (m *EmailResp) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailResp.DiscardUnknown(m)
}

var xxx_messageInfo_EmailResp proto.InternalMessageInfo

func (m *EmailResp) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func init() {
	proto.RegisterEnum("domain.EmailType", EmailType_name, EmailType_value)
	proto.RegisterType((*EmailParams)(nil), "domain.EmailParams")
	proto.RegisterType((*EmailResp)(nil), "domain.EmailResp")
}

func init() { proto.RegisterFile("emails.proto", fileDescriptor_ee0b3a5d3524f34c) }

var fileDescriptor_ee0b3a5d3524f34c = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4f, 0x4b, 0xf3, 0x40,
	0x18, 0xc4, 0xdf, 0xa4, 0x25, 0xd0, 0xa7, 0xa5, 0x6f, 0x7c, 0x3c, 0x18, 0x04, 0xa1, 0x56, 0x84,
	0xe2, 0x21, 0x81, 0xfa, 0x09, 0x62, 0xec, 0x49, 0x68, 0x4b, 0x52, 0xa9, 0x78, 0x91, 0x4d, 0xb2,
	0xb6, 0x8b, 0xd9, 0x3f, 0x64, 0x37, 0x48, 0xbf, 0xbd, 0xec, 0xa6, 0x97, 0xde, 0x86, 0xdf, 0xcc,
	0x0e, 0xb3, 0x0f, 0x4c, 0x28, 0x27, 0xac, 0xd1, 0xb1, 0x6a, 0xa5, 0x91, 0x18, 0xd4, 0x92, 0x13,
	0x26, 0xe6, 0x1f, 0x30, 0x5e, 0x59, 0xbe, 0x25, 0x2d, 0xe1, 0x1a, 0xa7, 0xe0, 0x53, 0x1e, 0x79,
	0x33, 0x6f, 0x31, 0xca, 0x7d, 0xca, 0x11, 0x61, 0xd8, 0x10, 0x71, 0x88, 0x7c, 0x47, 0x9c, 0xc6,
	0x47, 0x18, 0x9a, 0x93, 0xa2, 0xd1, 0x60, 0xe6, 0x2d, 0xa6, 0xcb, 0xab, 0xb8, 0x6f, 0x8a, 0x5d,
	0xcd, 0xee, 0xa4, 0x68, 0xee, 0xec, 0xf9, 0x1d, 0x8c, 0x1c, 0xca, 0xa9, 0x56, 0x18, 0xc2, 0xa0,
	0x63, 0xf5, 0xb9, 0xd8, 0xca, 0xa7, 0xf8, 0x6c, 0xdb, 0x17, 0xf8, 0x1f, 0xc6, 0xeb, 0xd5, 0xfe,
	0x2b, 0xcd, 0xb2, 0xcd, 0xfb, 0x7a, 0x17, 0xfe, 0xc3, 0x10, 0x26, 0x16, 0x6c, 0xd3, 0xa2, 0xd8,
	0x6f, 0xf2, 0xd7, 0xd0, 0x5b, 0xbe, 0x41, 0xe0, 0xf2, 0x1a, 0x53, 0xb8, 0x29, 0xa8, 0xa8, 0xd3,
	0xaa, 0x92, 0x9d, 0x30, 0x99, 0x14, 0xdf, 0xac, 0xe5, 0xc4, 0x30, 0x29, 0xf0, 0xfa, 0x62, 0x4c,
	0xff, 0xa7, 0xdb, 0xcb, 0x85, 0x76, 0xce, 0xcb, 0xc3, 0xe7, 0xfd, 0x81, 0x99, 0x63, 0x57, 0xc6,
	0x95, 0xe4, 0xc9, 0x4f, 0x43, 0x8e, 0x5a, 0x53, 0x91, 0xfc, 0xd2, 0x92, 0x28, 0x95, 0xf4, 0xf1,
	0x32, 0x70, 0x97, 0x7a, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x92, 0xb5, 0x15, 0x40, 0x39, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmailsClient is the client API for Emails service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmailsClient interface {
	SendAccountConfirmation(ctx context.Context, in *EmailParams, opts ...grpc.CallOption) (*EmailResp, error)
}

type emailsClient struct {
	cc *grpc.ClientConn
}

func NewEmailsClient(cc *grpc.ClientConn) EmailsClient {
	return &emailsClient{cc}
}

func (c *emailsClient) SendAccountConfirmation(ctx context.Context, in *EmailParams, opts ...grpc.CallOption) (*EmailResp, error) {
	out := new(EmailResp)
	err := c.cc.Invoke(ctx, "/domain.Emails/SendAccountConfirmation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailsServer is the server API for Emails service.
type EmailsServer interface {
	SendAccountConfirmation(context.Context, *EmailParams) (*EmailResp, error)
}

func RegisterEmailsServer(s *grpc.Server, srv EmailsServer) {
	s.RegisterService(&_Emails_serviceDesc, srv)
}

func _Emails_SendAccountConfirmation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailsServer).SendAccountConfirmation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/domain.Emails/SendAccountConfirmation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailsServer).SendAccountConfirmation(ctx, req.(*EmailParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Emails_serviceDesc = grpc.ServiceDesc{
	ServiceName: "domain.Emails",
	HandlerType: (*EmailsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendAccountConfirmation",
			Handler:    _Emails_SendAccountConfirmation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emails.proto",
}
